version: '3'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: npm run build && serve -s build
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - react